kubernetesClusterDomain: cluster.local
sampleWebApp:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 5000
  replicas: 1
  type: ClusterIP
  web:
    image:
      repository: nstarx.azurecr.io/nstarxpatch/sample_webapp
      tag: 0.1.0
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: azurecred
